// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOperation = `-- name: CreateOperation :execresult
insert into operation(
    account_id, amount
) values (
    ?, ?
)
`

type CreateOperationParams struct {
	AccountID uint32
	Amount    int64
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOperation, arg.AccountID, arg.Amount)
}

const deleteOperation = `-- name: DeleteOperation :execresult
delete from operation
where id = ?
`

func (q *Queries) DeleteOperation(ctx context.Context, id uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOperation, id)
}

const getOperation = `-- name: GetOperation :one
select id, account_id, amount, created_at from operation
where id = ?
limit 1
`

func (q *Queries) GetOperation(ctx context.Context, id uint32) (Operation, error) {
	row := q.db.QueryRowContext(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getOperations = `-- name: GetOperations :many
select id, account_id, amount, created_at from operation
order by id
limit ? offset ?
`

type GetOperationsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetOperations(ctx context.Context, arg GetOperationsParams) ([]Operation, error) {
	rows, err := q.db.QueryContext(ctx, getOperations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
