// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entry.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :execresult
insert into entry(
    account_id, amount
) values (
    ?, ?
)
`

type CreateEntryParams struct {
	AccountID uint32
	Amount    int64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEntry, arg.AccountID, arg.Amount)
}

const deleteEntry = `-- name: DeleteEntry :execresult
delete from entry
where id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEntry, id)
}

const getEntries = `-- name: GetEntries :many
select id, account_id, amount, created_at from entry
order by id
limit ? offset ?
`

type GetEntriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetEntries(ctx context.Context, arg GetEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
select id, account_id, amount, created_at from entry
where id = ?
limit 1
`

func (q *Queries) GetEntry(ctx context.Context, id uint32) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
