// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Account struct {
	ID        uint32
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        uint32
	AccountID uint32
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            uint32
	FromAccountID uint32
	ToAccountID   uint32
	Amount        uint64
	CreatedAt     time.Time
}
