// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transfer.sql

package db

import (
	"context"
	"database/sql"
)

const createTransfer = `-- name: CreateTransfer :execresult
insert into transfer(
    from_account_id, to_account_id, amount
) values (
    ?, ?, ?
)
`

type CreateTransferParams struct {
	FromAccountID uint32
	ToAccountID   uint32
	Amount        uint64
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransfer, arg.FromAccountID, arg.ToAccountID, arg.Amount)
}

const deleteTransfer = `-- name: DeleteTransfer :execresult
delete from transfer
where id = ?
`

func (q *Queries) DeleteTransfer(ctx context.Context, id uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTransfer, id)
}

const getTransfer = `-- name: GetTransfer :one
select id, from_account_id, to_account_id, amount, created_at from transfer
where id = ?
limit 1
`

func (q *Queries) GetTransfer(ctx context.Context, id uint32) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfers = `-- name: GetTransfers :many
select id, from_account_id, to_account_id, amount, created_at from transfer
order by id
limit ? offset ?
`

type GetTransfersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetTransfers(ctx context.Context, arg GetTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, getTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
